name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "hello world from issue 5" > helloworld.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b issue-5-fix
          git add helloworld.txt
          git commit -m "Suggested fix for issue #5"
          git push origin issue-5-fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Suggested fix for issue #5"
          branch: issue-5-fix
          base: main
          title: "Suggested fix for issue #5"
          body: "This PR suggests a fix for issue #5 by adding a helloworld.txt file."
          labels: bugfix, automated
